//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interop.Office.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ftnBoltNut_SaveAsmPath {
            get {
                return ((bool)(this["ftnBoltNut_SaveAsmPath"]));
            }
            set {
                this["ftnBoltNut_SaveAsmPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ftnBoltNut_AutoL {
            get {
                return ((bool)(this["ftnBoltNut_AutoL"]));
            }
            set {
                this["ftnBoltNut_AutoL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ftnBoltNut_selPath {
            get {
                return ((string)(this["ftnBoltNut_selPath"]));
            }
            set {
                this["ftnBoltNut_selPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrinterFiles {
            get {
                return ((string)(this["PrinterFiles"]));
            }
            set {
                this["PrinterFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Printer_chkSubPath {
            get {
                return ((bool)(this["Printer_chkSubPath"]));
            }
            set {
                this["Printer_chkSubPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrinterFolder {
            get {
                return ((string)(this["PrinterFolder"]));
            }
            set {
                this["PrinterFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A0")]
        public string Printer_cmbPrintWidth {
            get {
                return ((string)(this["Printer_cmbPrintWidth"]));
            }
            set {
                this["Printer_cmbPrintWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Printer_rdoInARow {
            get {
                return ((bool)(this["Printer_rdoInARow"]));
            }
            set {
                this["Printer_rdoInARow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Printer_chkAutoColor {
            get {
                return ((int)(this["Printer_chkAutoColor"]));
            }
            set {
                this["Printer_chkAutoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("890")]
        public int Printer_txtA0W {
            get {
                return ((int)(this["Printer_txtA0W"]));
            }
            set {
                this["Printer_txtA0W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("630")]
        public int Printer_txtA1W {
            get {
                return ((int)(this["Printer_txtA1W"]));
            }
            set {
                this["Printer_txtA1W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("430")]
        public int Printer_txtA2W {
            get {
                return ((int)(this["Printer_txtA2W"]));
            }
            set {
                this["Printer_txtA2W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("297")]
        public int Printer_txtA3W {
            get {
                return ((int)(this["Printer_txtA3W"]));
            }
            set {
                this["Printer_txtA3W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int Printer_txtA4W {
            get {
                return ((int)(this["Printer_txtA4W"]));
            }
            set {
                this["Printer_txtA4W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1230")]
        public int Printer_txtA0H {
            get {
                return ((int)(this["Printer_txtA0H"]));
            }
            set {
                this["Printer_txtA0H"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("870")]
        public int Printer_txtA1H {
            get {
                return ((int)(this["Printer_txtA1H"]));
            }
            set {
                this["Printer_txtA1H"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("610")]
        public int Printer_txtA2H {
            get {
                return ((int)(this["Printer_txtA2H"]));
            }
            set {
                this["Printer_txtA2H"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("430")]
        public int Printer_txtA3H {
            get {
                return ((int)(this["Printer_txtA3H"]));
            }
            set {
                this["Printer_txtA3H"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("297")]
        public int Printer_txtA4H {
            get {
                return ((int)(this["Printer_txtA4H"]));
            }
            set {
                this["Printer_txtA4H"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Printer_cmbSpaceXY {
            get {
                return ((int)(this["Printer_cmbSpaceXY"]));
            }
            set {
                this["Printer_cmbSpaceXY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Printer_cmbSpaceLT {
            get {
                return ((int)(this["Printer_cmbSpaceLT"]));
            }
            set {
                this["Printer_cmbSpaceLT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Printer_chkAddLine {
            get {
                return ((bool)(this["Printer_chkAddLine"]));
            }
            set {
                this["Printer_chkAddLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Symbol_LastNodePath {
            get {
                return ((string)(this["Symbol_LastNodePath"]));
            }
            set {
                this["Symbol_LastNodePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Symbol_bDisplayName {
            get {
                return ((bool)(this["Symbol_bDisplayName"]));
            }
            set {
                this["Symbol_bDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("699")]
        public int frmAll_width {
            get {
                return ((int)(this["frmAll_width"]));
            }
            set {
                this["frmAll_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("596")]
        public int frmAll_height {
            get {
                return ((int)(this["frmAll_height"]));
            }
            set {
                this["frmAll_height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("262")]
        public int frmAll_spltADisct {
            get {
                return ((int)(this["frmAll_spltADisct"]));
            }
            set {
                this["frmAll_spltADisct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("227")]
        public int frmAll_spltCDisct {
            get {
                return ((int)(this["frmAll_spltCDisct"]));
            }
            set {
                this["frmAll_spltCDisct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("382")]
        public int frmAll_spltBDisct {
            get {
                return ((int)(this["frmAll_spltBDisct"]));
            }
            set {
                this["frmAll_spltBDisct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCV_radioNewPath {
            get {
                return ((bool)(this["AutoCV_radioNewPath"]));
            }
            set {
                this["AutoCV_radioNewPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".PDF")]
        public string AutoCV_DefaultExt {
            get {
                return ((string)(this["AutoCV_DefaultExt"]));
            }
            set {
                this["AutoCV_DefaultExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".slddrw")]
        public string AutoCV_arExtensions {
            get {
                return ((string)(this["AutoCV_arExtensions"]));
            }
            set {
                this["AutoCV_arExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.31")]
        public string fntWeb_ServerIP {
            get {
                return ((string)(this["fntWeb_ServerIP"]));
            }
            set {
                this["fntWeb_ServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fntWeb_SavePath {
            get {
                return ((string)(this["fntWeb_SavePath"]));
            }
            set {
                this["fntWeb_SavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAddToolBar {
            get {
                return ((bool)(this["bAddToolBar"]));
            }
            set {
                this["bAddToolBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bShowStartForm {
            get {
                return ((bool)(this["bShowStartForm"]));
            }
            set {
                this["bShowStartForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bOnePartManyConf {
            get {
                return ((bool)(this["bOnePartManyConf"]));
            }
            set {
                this["bOnePartManyConf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double swBomRowLength {
            get {
                return ((double)(this["swBomRowLength"]));
            }
            set {
                this["swBomRowLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int swBomType_e {
            get {
                return ((int)(this["swBomType_e"]));
            }
            set {
                this["swBomType_e"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string strWorkPath {
            get {
                return ((string)(this["strWorkPath"]));
            }
            set {
                this["strWorkPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456789012")]
        public long exe1ength {
            get {
                return ((long)(this["exe1ength"]));
            }
            set {
                this["exe1ength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WriteTechnic_Line {
            get {
                return ((bool)(this["WriteTechnic_Line"]));
            }
            set {
                this["WriteTechnic_Line"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int exeStartx {
            get {
                return ((int)(this["exeStartx"]));
            }
            set {
                this["exeStartx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int exeStarty {
            get {
                return ((int)(this["exeStarty"]));
            }
            set {
                this["exeStarty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("328")]
        public int addPPage_width {
            get {
                return ((int)(this["addPPage_width"]));
            }
            set {
                this["addPPage_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int addPPage_height {
            get {
                return ((int)(this["addPPage_height"]));
            }
            set {
                this["addPPage_height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int swBomBomTemplate {
            get {
                return ((int)(this["swBomBomTemplate"]));
            }
            set {
                this["swBomBomTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True,True,True,3,1,False")]
        public string setUpInTolerance {
            get {
                return ((string)(this["setUpInTolerance"]));
            }
            set {
                this["setUpInTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("910")]
        public int fntWeb_width {
            get {
                return ((int)(this["fntWeb_width"]));
            }
            set {
                this["fntWeb_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("590")]
        public int fntWeb_height {
            get {
                return ((int)(this["fntWeb_height"]));
            }
            set {
                this["fntWeb_height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tolerance_bTopWindow {
            get {
                return ((bool)(this["Tolerance_bTopWindow"]));
            }
            set {
                this["Tolerance_bTopWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tolerance_bDisplayPC {
            get {
                return ((bool)(this["Tolerance_bDisplayPC"]));
            }
            set {
                this["Tolerance_bDisplayPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tolerance_bDisplayGCD {
            get {
                return ((bool)(this["Tolerance_bDisplayGCD"]));
            }
            set {
                this["Tolerance_bDisplayGCD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tolerance_bPCinKH {
            get {
                return ((bool)(this["Tolerance_bPCinKH"]));
            }
            set {
                this["Tolerance_bPCinKH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Tolerance_iPrecision {
            get {
                return ((int)(this["Tolerance_iPrecision"]));
            }
            set {
                this["Tolerance_iPrecision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Tolerance_iTaoHeStyle {
            get {
                return ((int)(this["Tolerance_iTaoHeStyle"]));
            }
            set {
                this["Tolerance_iTaoHeStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BOM_rdoCfgAtt {
            get {
                return ((bool)(this["BOM_rdoCfgAtt"]));
            }
            set {
                this["BOM_rdoCfgAtt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BOM_rdoListAtt {
            get {
                return ((bool)(this["BOM_rdoListAtt"]));
            }
            set {
                this["BOM_rdoListAtt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BOM_chkIgnoreAsm {
            get {
                return ((bool)(this["BOM_chkIgnoreAsm"]));
            }
            set {
                this["BOM_chkIgnoreAsm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$单重")]
        public string BOM_DZ {
            get {
                return ((string)(this["BOM_DZ"]));
            }
            set {
                this["BOM_DZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$总重")]
        public string BOM_ZZ {
            get {
                return ((string)(this["BOM_ZZ"]));
            }
            set {
                this["BOM_ZZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$数量小计")]
        public string BOM_SL {
            get {
                return ((string)(this["BOM_SL"]));
            }
            set {
                this["BOM_SL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AboutTabSelIndex {
            get {
                return ((int)(this["AboutTabSelIndex"]));
            }
            set {
                this["AboutTabSelIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("迈迪数码")]
        public string dwgtemplateCompanyName {
            get {
                return ((string)(this["dwgtemplateCompanyName"]));
            }
            set {
                this["dwgtemplateCompanyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RepName_txtNewStr {
            get {
                return ((string)(this["RepName_txtNewStr"]));
            }
            set {
                this["RepName_txtNewStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RepName_txtOldStr {
            get {
                return ((string)(this["RepName_txtOldStr"]));
            }
            set {
                this["RepName_txtOldStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RepName_txtFolderPath {
            get {
                return ((string)(this["RepName_txtFolderPath"]));
            }
            set {
                this["RepName_txtFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepName_bIncProperty {
            get {
                return ((bool)(this["RepName_bIncProperty"]));
            }
            set {
                this["RepName_bIncProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string XingWei_Level {
            get {
                return ((string)(this["XingWei_Level"]));
            }
            set {
                this["XingWei_Level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string WriteTech_LineDist {
            get {
                return ((string)(this["WriteTech_LineDist"]));
            }
            set {
                this["WriteTech_LineDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string WriteTech_TxtHeight {
            get {
                return ((string)(this["WriteTech_TxtHeight"]));
            }
            set {
                this["WriteTech_TxtHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public string WriteTech_LineTxtNbl {
            get {
                return ((string)(this["WriteTech_LineTxtNbl"]));
            }
            set {
                this["WriteTech_LineTxtNbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoCV_selpath {
            get {
                return ((string)(this["AutoCV_selpath"]));
            }
            set {
                this["AutoCV_selpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoCV_selMFiles {
            get {
                return ((string)(this["AutoCV_selMFiles"]));
            }
            set {
                this["AutoCV_selMFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Auto_bAllExtensions {
            get {
                return ((bool)(this["Auto_bAllExtensions"]));
            }
            set {
                this["Auto_bAllExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Auto_bChangeExten {
            get {
                return ((bool)(this["Auto_bChangeExten"]));
            }
            set {
                this["Auto_bChangeExten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Auto_arExtensions {
            get {
                return ((string)(this["Auto_arExtensions"]));
            }
            set {
                this["Auto_arExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string Auto_iLevel {
            get {
                return ((string)(this["Auto_iLevel"]));
            }
            set {
                this["Auto_iLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AddCode_RetCode {
            get {
                return ((string)(this["AddCode_RetCode"]));
            }
            set {
                this["AddCode_RetCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AddCode_CodePre {
            get {
                return ((string)(this["AddCode_CodePre"]));
            }
            set {
                this["AddCode_CodePre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AddCode_CodeLevel {
            get {
                return ((int)(this["AddCode_CodeLevel"]));
            }
            set {
                this["AddCode_CodeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AddCode_Sepeater {
            get {
                return ((string)(this["AddCode_Sepeater"]));
            }
            set {
                this["AddCode_Sepeater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public int swBomTitleBarHeight {
            get {
                return ((int)(this["swBomTitleBarHeight"]));
            }
            set {
                this["swBomTitleBarHeight"] = value;
            }
        }
        
        /// <summary>
        /// 是否点击图标显示工具条
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("是否点击图标显示工具条")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MDEXE_UseXuanGua {
            get {
                return ((bool)(this["MDEXE_UseXuanGua"]));
            }
            set {
                this["MDEXE_UseXuanGua"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string chkPanelIsActive {
            get {
                return ((string)(this["chkPanelIsActive"]));
            }
            set {
                this["chkPanelIsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string dblBomRowLength {
            get {
                return ((string)(this["dblBomRowLength"]));
            }
            set {
                this["dblBomRowLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int swBomRowCount1 {
            get {
                return ((int)(this["swBomRowCount1"]));
            }
            set {
                this["swBomRowCount1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int swBomRowCount2 {
            get {
                return ((int)(this["swBomRowCount2"]));
            }
            set {
                this["swBomRowCount2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580")]
        public string exeFormWidth_J {
            get {
                return ((string)(this["exeFormWidth_J"]));
            }
            set {
                this["exeFormWidth_J"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string Tolerance_bSmallWindow {
            get {
                return ((string)(this["Tolerance_bSmallWindow"]));
            }
            set {
                this["Tolerance_bSmallWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool frmAll_bUseCache {
            get {
                return ((bool)(this["frmAll_bUseCache"]));
            }
            set {
                this["frmAll_bUseCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("序号")]
        public string CreateNbr_PPtName {
            get {
                return ((string)(this["CreateNbr_PPtName"]));
            }
            set {
                this["CreateNbr_PPtName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string CreateNbr_StartIndex {
            get {
                return ((string)(this["CreateNbr_StartIndex"]));
            }
            set {
                this["CreateNbr_StartIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BOM_filterIdx {
            get {
                return ((int)(this["BOM_filterIdx"]));
            }
            set {
                this["BOM_filterIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelExtension {
            get {
                return ((string)(this["ExcelExtension"]));
            }
            set {
                this["ExcelExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BOM_chkIgnoreSuppressed {
            get {
                return ((bool)(this["BOM_chkIgnoreSuppressed"]));
            }
            set {
                this["BOM_chkIgnoreSuppressed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool fntWeb_dgvPptHid {
            get {
                return ((bool)(this["fntWeb_dgvPptHid"]));
            }
            set {
                this["fntWeb_dgvPptHid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool frmAll_bThreadMaps {
            get {
                return ((bool)(this["frmAll_bThreadMaps"]));
            }
            set {
                this["frmAll_bThreadMaps"] = value;
            }
        }
        
        /// <summary>
        /// 生成标准件后删除方程式（全局设置）
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("生成标准件后删除方程式（全局设置）")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmAll_bDelFormula {
            get {
                return ((bool)(this["frmAll_bDelFormula"]));
            }
            set {
                this["frmAll_bDelFormula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MDEXE_AutoHidden {
            get {
                return ((bool)(this["MDEXE_AutoHidden"]));
            }
            set {
                this["MDEXE_AutoHidden"] = value;
            }
        }
        
        /// <summary>
        /// 打开模型包默认选择的扩展名
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("打开模型包默认选择的扩展名")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int fntWeb_mdpgksfilter {
            get {
                return ((int)(this["fntWeb_mdpgksfilter"]));
            }
            set {
                this["fntWeb_mdpgksfilter"] = value;
            }
        }
        
        /// <summary>
        /// 记录每个功能的使用次数
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("记录每个功能的使用次数")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[1=0][15=0]")]
        public string MDExe_Times {
            get {
                return ((string)(this["MDExe_Times"]));
            }
            set {
                this["MDExe_Times"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MDEXE_UseBigIcon {
            get {
                return ((bool)(this["MDEXE_UseBigIcon"]));
            }
            set {
                this["MDEXE_UseBigIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int exeOSBit {
            get {
                return ((int)(this["exeOSBit"]));
            }
            set {
                this["exeOSBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Login_SavePWD {
            get {
                return ((bool)(this["Login_SavePWD"]));
            }
            set {
                this["Login_SavePWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login_strPWD {
            get {
                return ((string)(this["Login_strPWD"]));
            }
            set {
                this["Login_strPWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login_strName {
            get {
                return ((string)(this["Login_strName"]));
            }
            set {
                this["Login_strName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DimMgrSelArr {
            get {
                return ((string)(this["DimMgrSelArr"]));
            }
            set {
                this["DimMgrSelArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HuaDong_2dChecked {
            get {
                return ((string)(this["HuaDong_2dChecked"]));
            }
            set {
                this["HuaDong_2dChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StrReplace_cfg {
            get {
                return ((string)(this["StrReplace_cfg"]));
            }
            set {
                this["StrReplace_cfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BomWritePPT_cfg {
            get {
                return ((string)(this["BomWritePPT_cfg"]));
            }
            set {
                this["BomWritePPT_cfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("毛重")]
        public string HuaDong_MaoZhongPPT {
            get {
                return ((string)(this["HuaDong_MaoZhongPPT"]));
            }
            set {
                this["HuaDong_MaoZhongPPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("名称")]
        public string HuaDong_XYZPPT {
            get {
                return ((string)(this["HuaDong_XYZPPT"]));
            }
            set {
                this["HuaDong_XYZPPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("纸张大小")]
        public string HuaDong_DwgSize {
            get {
                return ((string)(this["HuaDong_DwgSize"]));
            }
            set {
                this["HuaDong_DwgSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"工程图号\"\"版本号\"")]
        public string saidi_cmbNameType {
            get {
                return ((string)(this["saidi_cmbNameType"]));
            }
            set {
                this["saidi_cmbNameType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DimMgr_AllViews {
            get {
                return ((bool)(this["DimMgr_AllViews"]));
            }
            set {
                this["DimMgr_AllViews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DimMgr_DuplicateDims {
            get {
                return ((bool)(this["DimMgr_DuplicateDims"]));
            }
            set {
                this["DimMgr_DuplicateDims"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DimMgr_HiddenFeatureDims {
            get {
                return ((bool)(this["DimMgr_HiddenFeatureDims"]));
            }
            set {
                this["DimMgr_HiddenFeatureDims"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DimMgr_Option {
            get {
                return ((int)(this["DimMgr_Option"]));
            }
            set {
                this["DimMgr_Option"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DimMgr_UsePlacementInSketch {
            get {
                return ((bool)(this["DimMgr_UsePlacementInSketch"]));
            }
            set {
                this["DimMgr_UsePlacementInSketch"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.my3dparts.com/asmx/MDTool.asmx")]
        public string Interop_Office_Core_my3dparts_MDTool {
            get {
                return ((string)(this["Interop_Office_Core_my3dparts_MDTool"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BOM_chkIgnoreSubWeldment {
            get {
                return ((bool)(this["BOM_chkIgnoreSubWeldment"]));
            }
            set {
                this["BOM_chkIgnoreSubWeldment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BOM_chkCurrConfig {
            get {
                return ((bool)(this["BOM_chkCurrConfig"]));
            }
            set {
                this["BOM_chkCurrConfig"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.my3dparts.com/asmx/MDTool.asmx")]
        public string AutoPartNo_my3dparts_MDTool {
            get {
                return ((string)(this["AutoPartNo_my3dparts_MDTool"]));
            }
        }
    }
}
